name: pratica-api

services:
  pratica-app:
    build:
      context: ./
      dockerfile: dockerfile

    ports: 
      - 3001:3001

    volumes:
      - .:/app

    networks:
      - bridge_connect

    env_file:
      - ./.env

  postgres-database:
    image: postgres:16.3

    ports:
      - 5432:5432
    
    restart: always

    shm_size: 128mb

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres

    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data

    networks:
      - bridge_connect
  
  postgres-admin:
    image: elestio/pgadmin:latest

    ports:
      - 8080:8080

    environment:
      PGADMIN_DEFAULT_EMAIL: p@p.com
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_LISTEN_PORT: 8080

    networks:
      - bridge_connect

networks:
  bridge_connect:
    driver: bridge